FROM ubuntu:22.04

#
# Skip interactive mode
#
ENV DEBIAN_FRONTEND=noninteractive


#
# Install Nginx and latest PHP version 8.1.2
#
RUN apt-get update		    \
    && apt-get install -y	\
    nginx			        \
    sqlite3			        \
    php8.1-fpm		        \
    php8.1-mysql		    \
    php8.1-intl			    \
    php8.1-mbstring		    \
    php8.1-zip		        \
    php8.1-xml		        \
    php8.1-sqlite3

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/php.ini /etc/php/8.1/fpm/php.ini
COPY docker/php_cli.ini /etc/php/8.1/cli/php.ini
COPY docker/default /etc/nginx/sites-available/default
COPY docker/mhsendmail /usr/local/bin/mhsendmail

EXPOSE 80

#
# Adding MailHog support
# set default address to 127.0.0.1
#
ENV MAILHOG_SMTP_IP_ADDR=127.0.0.1

WORKDIR /var/www/html

CMD service php8.1-fpm start 	\
    && nginx -g 'daemon off;'	\
    && bash
